version: "3.9"
services:
  db:
    image: postgres:15
    container_name: ahp_app
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Password_123
      POSTGRES_DB: ahp_app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
